"""Stand-ins for Ollama, the HuggingFace API and LLMs, shaped like the real responses recorded
on 2026-09-11 (parameter counts, config model types, base_model tags)."""
import json

import httpx

from src.grading.subjective_grader import LLM_SCHEMA
from src.models.ollama_probe import ModelIdentity, VRAMMeasurement

QWEN = ModelIdentity("qwen3.5:9b", "qwen35", "qwen35", "9.7B", 9653104368, "Q4_K_M", 262144,
                     ("completion", "vision", "tools", "thinking"))
GEMMA = ModelIdentity("gemma4:e4b", "gemma4", "gemma4", "8.0B", 7996157674, "Q4_K_M", 131072,
                      ("completion", "vision", "audio", "tools", "thinking"))
TINY = ModelIdentity("tiny:1b", "tinyfam", "tinyfam", "1.0B", 1_000_000_000, "Q4_0", 4096, ("completion",))

QWEN_MODELFILE = '''# Modelfile generated by "ollama show"
FROM G:\\models\\blobs\\sha256-dec52a
TEMPLATE {{ .Prompt }}
RENDERER qwen3.5
PARSER qwen3.5
PARAMETER temperature 1
PARAMETER top_k 20
LICENSE """                                Apache License
   TERMS AND CONDITIONS FOR USE, REPRODUCTION
"""
'''


def hf(repo, total=None, model_type=None, tags=(), downloads=1000, gated=False):
    entry = {"id": repo, "downloads": downloads, "gated": gated, "tags": list(tags),
             "config": {"model_type": model_type} if model_type else {}}
    if total:
        entry["safetensors"] = {"total": total}
    return entry


HF_REPOS = [
    hf("Qwen/Qwen3.5-9B", 9653104368, "qwen3_5", ["transformers", "base_model:Qwen/Qwen3.5-9B-Base",
                                                  "base_model:finetune:Qwen/Qwen3.5-9B-Base"], 10_922_333),
    hf("Qwen/Qwen3.5-9B-Base", 9653104368, "qwen3_5", ["transformers"], 400_000),
    hf("Qwen/Qwen3.5-4B", 4659865088, "qwen3_5", ["base_model:Qwen/Qwen3.5-4B-Base"], 7_205_448),
    hf("unsloth/Qwen3.5-9B-GGUF", None, None, ["gguf", "base_model:quantized:Qwen/Qwen3.5-9B"], 1_634_867),
    hf("QuantTrio/Qwen3.5-9B-AWQ", 9653104368, "qwen3_5", ["awq", "4-bit", "base_model:quantized:Qwen/Qwen3.5-9B"], 90_000),
    hf("HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive", 9653104368, "qwen3_5",
       ["base_model:finetune:Qwen/Qwen3.5-9B"], 800_000),
    hf("google/gemma-4-E4B-it", 7996156490, "gemma4", ["base_model:google/gemma-4-E4B",
                                                       "base_model:finetune:google/gemma-4-E4B"], 3_000_000),
    hf("google/gemma-4-E4B", 7996156490, "gemma4", [], 3_100_000),
    hf("lmstudio-community/gemma-4-E4B-it-MLX-4bit", 1_500_000_000, "gemma4",
       ["mlx", "base_model:quantized:google/gemma-4-E4B-it"], 50_000),
    hf("google/gemma-4-26B-A4B-it", 26_000_000_000, "gemma4", [], 2_000_000),
]


class FakeHF:
    """httpx MockTransport for huggingface.co/api/models; records every request."""

    def __init__(self, repos=HF_REPOS, fail=False):
        self.repos = {r["id"]: r for r in repos}
        self.fail = fail
        self.requests = []

    def __call__(self, request: httpx.Request) -> httpx.Response:
        self.requests.append(request)
        if self.fail:
            raise httpx.ConnectError("offline", request=request)
        path = request.url.path
        if path == "/api/models":
            term = request.url.params["search"].lower().replace("-", "").replace(".", "")
            hits = [r for r in self.repos.values()
                    if term in r["id"].lower().replace("-", "").replace(".", "")]
            return httpx.Response(200, json=sorted(hits, key=lambda r: -r["downloads"]))
        repo = path.removeprefix("/api/models/")
        if repo in self.repos:
            return httpx.Response(200, json=self.repos[repo])
        return httpx.Response(401, json={"error": "Invalid username or password."})

    def client(self) -> httpx.Client:
        return httpx.Client(base_url="https://huggingface.co", transport=httpx.MockTransport(self))


class FakeProbe:
    def __init__(self, identities=(QWEN, GEMMA, TINY)):
        self.identities = {i.name: i for i in identities}
        self.removed, self.pulled = [], []

    def digests(self):
        return {name: f"sha-{name}" for name in self.identities}

    def list_models(self):
        return list(self.identities)

    def probe(self, name):
        if name not in self.identities:
            raise KeyError(name)
        return self.identities[name]

    def show(self, name):
        return {"modelfile": QWEN_MODELFILE}

    def remove(self, name):
        self.removed.append(name)

    def pull(self, name, on_progress=None):
        for done in (0, 50, 100):
            on_progress and on_progress("pulling", done, 100)
        self.pulled.append(name)

    def measure_vram(self, name, num_ctx=8192):
        return VRAMMeasurement(name, num_ctx, 3 * 2**30, 3 * 2**30, 1.0)

    def unload(self, name):
        pass


def _text(messages):
    content = messages[-1]["content"]
    if isinstance(content, list):
        return " ".join(p.get("text", "[image]") for p in content), True
    return content, False


class GoodLLM:
    """Behaves like qwen3.5:9b did in the live probe: native JSON, exact formats, sane marks."""

    def __init__(self, sees_images=True, fenced=False):
        self.sees_images = sees_images
        self.fenced = fenced
        self.calls = 0

    def _json(self, data):
        text = json.dumps(data)
        return f"```json\n{text}\n```" if self.fenced else text

    def __call__(self, messages, schema=None):
        self.calls += 1
        text, has_image = _text(messages)
        if schema == LLM_SCHEMA:
            student = text.split("<student_answer>")[-1]
            quality = 1.0 if "chloroplasts" in student else 0.0 if "break down glucose" in student else 0.4
            return self._json({"quality": quality, "feedback": "ok", "missing_points": []})
        if schema:
            required = set(schema["required"])
            if "out_of" in required:
                return self._json({"name": "Riya", "score": 14, "out_of": 20, "subject": "Biology"})
            if "tone" in required:
                return self._json({"tone": "positive", "reason": "praise"})
            return self._json({"items": ["solid", "liquid", "gas"]})
        if has_image:
            return "MITOSIS" if self.sees_images else "I cannot see the image."
        if "BANANA" in text:
            return "BANANA"
        if "17 + 25" in text:
            return "42"
        if "primary colours" in text:
            return "Red\nGreen\nBlue"
        if "access code" in text:
            return "4172"
        return "OK"


class BadLLM:
    """A chatty model: prose instead of JSON, ignores format rules, marks everything 5/5."""

    def __call__(self, messages, schema=None):
        return "Sure! Here is my answer. I think this deserves full marks: it's great."
